// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	_ "github.com/lib/pq"
)

// Injectors from wireInject.go:

func setupApplication(flags *cliFlags) (*application, error) {
	mainEnvName := provideName(flags)
	db, err := provideAppDB()
	if err != nil {
		return nil, err
	}
	level := provideLogLevel(flags)
	logger := provideLogger(level)
	router := provideRouter(db, logger)
	mainApplication := provideApplication(mainEnvName, router, db, logger)
	return mainApplication, nil
}
