// Code generated by sqlc. DO NOT EDIT.

package moviestore

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	MovieID         uuid.UUID
	ExtlID          string
	Title           string
	Rated           sql.NullString
	Released        sql.NullTime
	RunTime         sql.NullInt32
	Director        sql.NullString
	Writer          sql.NullString
	CreateAppID     uuid.UUID
	CreateUserID    uuid.NullUUID
	CreateTimestamp time.Time
	UpdateAppID     uuid.UUID
	UpdateUserID    uuid.NullUUID
	UpdateTimestamp time.Time
}
