// Code generated by sqlc. DO NOT EDIT.

package appstore

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// app stores data about applications that interact with the system
type App struct {
	AppID           uuid.UUID
	OrgID           uuid.UUID
	AppExtlID       string
	AppName         string
	AppDescription  string
	Active          sql.NullBool
	CreateAppID     uuid.UUID
	CreateUserID    uuid.NullUUID
	CreateTimestamp time.Time
	UpdateAppID     uuid.UUID
	UpdateUserID    uuid.NullUUID
	UpdateTimestamp time.Time
}

type AppApiKey struct {
	// app_key is a hash of a key given to a user for an app
	ApiKey string
	// foreign key to app table
	AppID           uuid.UUID
	DeactvDate      time.Time
	CreateAppID     uuid.UUID
	CreateUserID    uuid.NullUUID
	CreateTimestamp time.Time
	UpdateAppID     uuid.UUID
	UpdateUserID    uuid.NullUUID
	UpdateTimestamp time.Time
}

type Org struct {
	OrgID           uuid.UUID
	OrgExtlID       string
	OrgName         string
	OrgDescription  string
	CreateAppID     uuid.UUID
	CreateUserID    uuid.NullUUID
	CreateTimestamp time.Time
	UpdateAppID     uuid.UUID
	UpdateUserID    uuid.NullUUID
	UpdateTimestamp time.Time
}
